version: '2'
services:

  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - /root/nginx/html:/usr/share/nginx/html
    - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  mysql:
    image: mysql:8.0.18
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=123

  #redis容器
  redis:
    #定义主机名
    hostname: myredis
    #使用的镜像
    image: redis:6.0.6
    #容器的映射端口
    ports:
      - 6381:6379
    restart: always
    #定义挂载点
    volumes:
      - ./data:/data
    #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
  vueblog:
    image: tomorrow:latest
    build: .
    ports:
    - 8181:8181

    depends_on:
      - mysql
      - redis
